### ISSUE TITLE
Not compatible with Samsung S6

### ISSUE THREAD

**Issue by ajhodges** [ajhodges/WifiCallingControls#15]
Got multiple bug reports with NullPointerExceptions:
`java.lang.RuntimeException: Unable to start receiver com.ajhodges.wificallingcontrols.widget.ToggleWidgetProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3114)
at android.app.ActivityThread.access$1800(ActivityThread.java:181)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6117)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
at com.ajhodges.wificallingcontrols.ipphone.SamsungCallingManager.getIPPhoneEnabled(SamsungCallingManager.java:65)
at com.ajhodges.wificallingcontrols.widget.ToggleWidgetProvider.update(ToggleWidgetProvider.java:67)
at com.ajhodges.wificallingcontrols.widget.ToggleWidgetProvider.onReceive(ToggleWidgetProvider.java:49)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3107)
... 9 more`

**Comment by thapar** [comment]
Any progress on this?

**Comment by ajhodges** [comment]
Unfortunately no... I'm going to need a T-Mobile S6 in order to debug this and I don't know anyone who has one. Hopefully another developer sees this and tries to tackle it.

**Comment by ajhodges** [comment]
@thapar this should be resolved in the latest release (just pushed to play store and uploaded to GitHub as well). Just as a note, this app still requires a rooted device, and the app must be moved to the system app folder in order to work on Samsung devices. Completely out of my control with no work-around :(
